/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search image records */
        get: operations["catalog_list_images"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One image record */
        get: operations["catalog_get_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All collections */
        get: operations["catalog_list_collections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One collection */
        get: operations["catalog_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release history */
        get: operations["catalog_list_releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter facets and their counts */
        get: operations["catalog_get_facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["admin_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the session */
        post: operations["admin_auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["admin_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["admin_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse records, including retired ones */
        get: operations["admin_catalog_list_images"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One record, with editable metadata */
        get: operations["admin_catalog_get_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a record's provenance */
        patch: operations["admin_catalog_update_image"];
        trace?: never;
    };
    "/api/v1/admin/images/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply provenance to many records */
        post: operations["admin_catalog_bulk_update_images"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/{record_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide a record from the public API */
        post: operations["admin_catalog_retire_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/{record_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return a record to the archive */
        post: operations["admin_catalog_restore_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/{record_id}/artifacts/{artifact_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Attach or replace a frame or mask */
        put: operations["admin_catalog_upload_artifact"];
        post?: never;
        /** Remove a frame or mask */
        delete: operations["admin_catalog_remove_artifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collections with their release history */
        get: operations["admin_catalog_list_collections"];
        put?: never;
        /** Create a collection */
        post: operations["admin_catalog_create_collection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a collection's metadata */
        patch: operations["admin_catalog_update_collection"];
        trace?: never;
    };
    "/api/v1/admin/collections/{slug}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a draft release */
        post: operations["admin_catalog_create_release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/releases/{release_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish or retire a release */
        post: operations["admin_catalog_transition_release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a draft release */
        delete: operations["admin_catalog_delete_release"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who changed what */
        get: operations["admin_catalog_list_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every vocabulary and its terms */
        get: operations["admin_vocabulary_list_vocabularies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One vocabulary */
        get: operations["admin_vocabulary_list_terms"];
        put?: never;
        /** Add a term */
        post: operations["admin_vocabulary_create_term"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/terms/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a term */
        patch: operations["admin_vocabulary_rename_term"];
        trace?: never;
    };
    "/api/v1/admin/vocabulary/terms/{term_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge one term into another */
        post: operations["admin_vocabulary_merge_term"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/terms/{term_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a term out of use */
        post: operations["admin_vocabulary_retire_term"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/terms/{term_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return a term to use */
        post: operations["admin_vocabulary_restore_term"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/{kind}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder a vocabulary */
        post: operations["admin_vocabulary_reorder_terms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every account */
        get: operations["admin_users_list_users"];
        put?: never;
        /** Invite someone */
        post: operations["admin_users_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a name, a role, or access */
        patch: operations["admin_users_update_user"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password */
        post: operations["admin_users_reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["catalog_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactOut */
        ArtifactOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "source" | "mask";
            /**
             * Url
             * @description Where the file is served from.
             */
            url: string;
            /**
             * Objectkey
             * @description Key within the object store.
             */
            objectKey: string;
            /** Bytes */
            bytes: number;
            /**
             * Checksum
             * @description SHA-256 of the delivered file.
             */
            checksum: string;
            /** Mediatype */
            mediaType: string;
        };
        /** Body_admin_catalog_upload_artifact */
        Body_admin_catalog_upload_artifact: {
            /** File */
            file: string;
        };
        /**
         * BulkImageEdit
         * @description Apply the same provenance to many frames.
         *
         *     A capture team supplies a site or an instrument for a whole sequence at
         *     once, not frame by frame; doing it one request at a time would be both slow
         *     and a worse audit trail.
         */
        BulkImageEdit: {
            /** Ids */
            ids: string[];
            changes: components["schemas"]["ImageRecordWrite"];
            /**
             * Tagmode
             * @default add
             * @enum {string}
             */
            tagMode: "add" | "replace" | "remove";
        };
        /** ClassProbabilityOut */
        ClassProbabilityOut: {
            /**
             * Skyclass
             * @description A SKY_CLASS vocabulary label, e.g. 'Stratocumulus'.
             */
            skyClass: string;
            /** Probability */
            probability: number;
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Locationname */
            locationName?: string | null;
            /** Latitude */
            latitude?: number | string | null;
            /** Longitude */
            longitude?: number | string | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
            /** Methodsurl */
            methodsUrl?: string | null;
            /** Publicationurl */
            publicationUrl?: string | null;
            /** Position */
            position?: number | null;
            /** Slug */
            slug: string;
        };
        /** CollectionEnvelope */
        CollectionEnvelope: {
            data: components["schemas"]["CollectionOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** CollectionListEnvelope */
        CollectionListEnvelope: {
            /** Data */
            data: components["schemas"]["CollectionSummaryOut"][];
            meta: components["schemas"]["CountMeta"];
            links: components["schemas"]["Links"];
        };
        /** CollectionOut */
        CollectionOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Shorttitle */
            shortTitle: string;
            /** Kicker */
            kicker: string;
            /** Description */
            description: string;
            /** Coverage */
            coverage: string;
            /** Sequenceids */
            sequenceIds: string[];
            /** Images */
            images: number;
            /** Artifacts */
            artifacts: number;
            /** Withsource */
            withSource: number;
            /**
             * Segmented
             * @description Records carrying a mask, and so a measurement.
             */
            segmented: number;
            /** Image */
            image: string;
            /** Imagealt */
            imageAlt: string;
            /**
             * Releases
             * @default []
             */
            releases: components["schemas"]["ReleaseOut"][];
            /**
             * Meancloudcoveroktas
             * @description Mean measured cover across the segmented frames.
             */
            meanCloudCoverOktas?: number | null;
            /**
             * Maskregistration
             * @default []
             */
            maskRegistration: components["schemas"]["MaskRegistration"][];
            /** Locationname */
            locationName?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
        };
        /**
         * CollectionSummaryOut
         * @description The listing shape: the release history replaced by the current one.
         */
        CollectionSummaryOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Shorttitle */
            shortTitle: string;
            /** Kicker */
            kicker: string;
            /** Description */
            description: string;
            /** Coverage */
            coverage: string;
            /** Sequenceids */
            sequenceIds: string[];
            /** Images */
            images: number;
            /** Artifacts */
            artifacts: number;
            /** Withsource */
            withSource: number;
            /**
             * Segmented
             * @description Records carrying a mask, and so a measurement.
             */
            segmented: number;
            /** Image */
            image: string;
            /** Imagealt */
            imageAlt: string;
            /**
             * Releases
             * @default []
             */
            releases: components["schemas"]["ReleaseOut"][];
            /**
             * Meancloudcoveroktas
             * @description Mean measured cover across the segmented frames.
             */
            meanCloudCoverOktas?: number | null;
            /**
             * Maskregistration
             * @default []
             */
            maskRegistration: components["schemas"]["MaskRegistration"][];
            /** Locationname */
            locationName?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
            currentRelease?: components["schemas"]["ReleaseOut"] | null;
        };
        /**
         * CollectionWrite
         * @description Editorial metadata for a sequence.
         *
         *     These are the fields that are NULL for every sequence today - the gap the
         *     dashboard exists to close.
         */
        CollectionWrite: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Locationname */
            locationName?: string | null;
            /** Latitude */
            latitude?: number | string | null;
            /** Longitude */
            longitude?: number | string | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
            /** Methodsurl */
            methodsUrl?: string | null;
            /** Publicationurl */
            publicationUrl?: string | null;
            /** Position */
            position?: number | null;
        };
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** CountMeta */
        CountMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Count */
            count: number;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: string[];
            } | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FacetValue */
        FacetValue: {
            /** Value */
            value: string | number;
            /** Label */
            label?: string | null;
            /** Count */
            count: number;
        };
        /** FacetsEnvelope */
        FacetsEnvelope: {
            data: components["schemas"]["FacetsOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** FacetsOut */
        FacetsOut: {
            /** Collections */
            collections: components["schemas"]["FacetValue"][];
            /** Sequences */
            sequences: components["schemas"]["FacetValue"][];
            /** Cloudcoveroktas */
            cloudCoverOktas: components["schemas"]["FacetValue"][];
            /** Segmentation */
            segmentation: components["schemas"]["FacetValue"][];
            /** Artifacts */
            artifacts: components["schemas"]["FacetValue"][];
            /** Seasons */
            seasons: components["schemas"]["FacetValue"][];
            /** Timesofday */
            timesOfDay: components["schemas"]["FacetValue"][];
            /** Skyclasses */
            skyClasses: components["schemas"]["FacetValue"][];
            /** Locations */
            locations: components["schemas"]["FacetValue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageEnvelope */
        ImageEnvelope: {
            data: components["schemas"]["ImageRecordOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** ImagePage */
        ImagePage: {
            /** Data */
            data: components["schemas"]["ImageRecordOut"][];
            meta: components["schemas"]["PageMeta"];
            links: components["schemas"]["PageLinks"];
        };
        /**
         * ImageRecordOut
         * @description One frame.
         *
         *     ``cloudFraction`` and ``cloudCoverOktas`` are absent, not null, on a frame
         *     that carries no mask: cloud cover is measured from the mask, so without one
         *     there is no measurement to report. They are never defaulted to zero, which
         *     would invent a clear sky.
         *
         *     ``observedCloudCoverOktas`` is the separate, human-supplied count that
         *     travels with the observer's cloud-genus label. It is never reconciled
         *     against the measured pair: the two can and do differ, and which one a
         *     reader wants depends on what they are checking.
         *
         *     ``predictions`` appears on the single-record read only. The list endpoints
         *     omit it rather than serialise one entry per class per model for every card
         *     on the page.
         */
        ImageRecordOut: {
            /** Id */
            id: string;
            /** Collection */
            collection: string;
            /** Release */
            release: string;
            /** Sequenceid */
            sequenceId: string;
            /** Frameindex */
            frameIndex: number;
            /** Cloudfraction */
            cloudFraction?: number | null;
            /** Cloudcoveroktas */
            cloudCoverOktas?: number | null;
            /** Observedcloudcoveroktas */
            observedCloudCoverOktas?: number | null;
            /**
             * Maskscale
             * @description Scale at which the mask was delivered relative to its frame. 1 for a correctly registered sequence; greater where the mask was rendered larger and the viewer must scale it back.
             */
            maskScale: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Image
             * @description Primary listing image: the frame, else the mask.
             */
            image: string;
            /** Sourceurl */
            sourceUrl?: string | null;
            /** Maskurl */
            maskUrl?: string | null;
            /** Hassource */
            hasSource: boolean;
            /** Hasmask */
            hasMask: boolean;
            /** Alt */
            alt: string;
            /** Tags */
            tags: string[];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactOut"][];
            /**
             * Sortkey
             * @description Capture time when known, sequence position otherwise.
             */
            sortKey: string;
            /** Capturedat */
            capturedAt?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Season */
            season?: string | null;
            /** Timeofday */
            timeOfDay?: string | null;
            /** Skyclass */
            skyClass?: string | null;
            /** Predictions */
            predictions?: components["schemas"]["PredictionOut"][] | null;
            /** Instrument */
            instrument?: string | null;
        };
        /**
         * ImageRecordWrite
         * @description Provenance a curator supplies for a frame.
         *
         *     Nothing here can invent a measurement: the cloud cover derived from the
         *     mask is not settable, and there is no field for it. What a person knows
         *     and a pipeline does not - where the camera was, when it was pointed at the
         *     sky, what it was, what they saw when they looked up - is what this
         *     carries.
         *
         *     ``observedCloudCoverOktas`` is the one number here, and it is an
         *     observation rather than a measurement: a count a person read off the sky,
         *     correcting or supplying what the label table loaded. It writes to its own
         *     column and leaves ``cloudCoverOktas`` alone.
         */
        ImageRecordWrite: {
            /** Capturedat */
            capturedAt?: string | null;
            /** Latitude */
            latitude?: number | string | null;
            /** Longitude */
            longitude?: number | string | null;
            /** Instrument */
            instrument?: string | null;
            /** Location */
            location?: string | null;
            /** Season */
            season?: string | null;
            /** Timeofday */
            timeOfDay?: string | null;
            /** Skyclass */
            skyClass?: string | null;
            /** Observedcloudcoveroktas */
            observedCloudCoverOktas?: number | null;
            /** Conditiontags */
            conditionTags?: string[] | null;
            /** Custom */
            custom?: {
                [key: string]: unknown;
            } | null;
        };
        /** Links */
        Links: {
            /** Self */
            self: string;
        };
        /** MaskRegistration */
        MaskRegistration: {
            /** Sequenceid */
            sequenceId: string;
            /**
             * Scale
             * @description Mask size relative to the frame it segments. 1 when registered.
             */
            scale: number;
            /** Corrected */
            corrected: boolean;
        };
        /** Meta */
        Meta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
        };
        /** PageLinks */
        PageLinks: {
            /** Self */
            self: string;
            /** Next */
            next?: string | null;
        };
        /** PageMeta */
        PageMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Count */
            count: number;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /**
         * PredictionModelOut
         * @description The classifier a probability vector came from.
         */
        PredictionModelOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Version
             * @description The model's own version string: a tag, a date or a commit.
             */
            version: string;
            /** Description */
            description?: string | null;
        };
        /**
         * PredictionOut
         * @description One model's reading of one frame.
         *
         *     ``classes`` is the whole vector, ranked by probability descending - every
         *     class the model scored, not just the winner. An all-sky frame routinely
         *     holds several genera at once, so the runners-up are the point: they are
         *     what makes the reading comparable with the observer's own.
         */
        PredictionOut: {
            model: components["schemas"]["PredictionModelOut"];
            /** Classes */
            classes: components["schemas"]["ClassProbabilityOut"][];
        };
        /** ReleaseCreate */
        ReleaseCreate: {
            /** Version */
            version: string;
            /** Capturestart */
            captureStart?: string | null;
            /** Captureend */
            captureEnd?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ReleaseListEnvelope */
        ReleaseListEnvelope: {
            /** Data */
            data: components["schemas"]["ReleaseOut"][];
            meta: components["schemas"]["ReleaseMeta"];
            links: components["schemas"]["Links"];
        };
        /** ReleaseMeta */
        ReleaseMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Collection */
            collection: string;
            /** Count */
            count: number;
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Version */
            version: string;
            /** Images */
            images: number;
            /**
             * Size
             * @description Human-readable total, e.g. '10.4 MB'.
             */
            size: string;
            /** Current */
            current: boolean;
            /** Publishedat */
            publishedAt?: string | null;
        };
        /** ReleaseTransition */
        ReleaseTransition: {
            /**
             * Status
             * @enum {string}
             */
            status: "PUBLISHED" | "RETIRED";
            /**
             * Current
             * @default true
             */
            current: boolean;
        };
        /**
         * UserCreate
         * @description Invite someone. The generated password comes back once in the response.
         */
        UserCreate: {
            /** Email */
            email: string;
            /** Fullname */
            fullName?: string | null;
            /** Role */
            role: string;
        };
        /**
         * UserUpdate
         * @description Change a name, a role, or whether the account may sign in.
         *
         *     Every field is optional and the router reads ``exclude_unset``, so omitting
         *     a field leaves it alone rather than clearing it.
         */
        UserUpdate: {
            /** Fullname */
            fullName?: string | null;
            /** Role */
            role?: string | null;
            /** Isactive */
            isActive?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VocabularyMerge
         * @description Fold one term into another.
         *
         *     Nothing is deleted: the losing term is retired, pointed at the winner, and
         *     its label kept as an alias, so a bookmarked query for the old value keeps
         *     resolving.
         */
        VocabularyMerge: {
            /** Intoid */
            intoId: string;
        };
        /** VocabularyReorder */
        VocabularyReorder: {
            /** Ids */
            ids: string[];
        };
        /** VocabularyTermWrite */
        VocabularyTermWrite: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Position */
            position?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_list_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePage"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    catalog_get_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_list_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListEnvelope"];
                };
            };
        };
    };
    catalog_get_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_list_releases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseListEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_get_facets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsEnvelope"];
                };
            };
        };
    };
    admin_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wascat_rt?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                wascat_rt?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_catalog_list_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_catalog_get_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_update_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageRecordWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_bulk_update_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkImageEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_retire_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_restore_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_upload_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
                artifact_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_admin_catalog_upload_artifact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_remove_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
                artifact_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_list_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_catalog_create_collection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_update_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_create_release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_transition_release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseTransition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_delete_release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_catalog_list_audit: {
        parameters: {
            query?: {
                entityType?: string | null;
                entityId?: string | null;
                action?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_list_vocabularies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_vocabulary_list_terms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_create_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyTermWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_rename_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyTermWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_merge_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyMerge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_retire_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_restore_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_vocabulary_reorder_terms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_users_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
