/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search image records */
        get: operations["catalog_list_images"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One image record */
        get: operations["catalog_get_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All collections */
        get: operations["catalog_list_collections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One collection */
        get: operations["catalog_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Release history */
        get: operations["catalog_list_releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter facets and their counts */
        get: operations["catalog_get_facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["catalog_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactOut */
        ArtifactOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "source" | "mask";
            /**
             * Url
             * @description Where the file is served from.
             */
            url: string;
            /**
             * Objectkey
             * @description Key within the object store.
             */
            objectKey: string;
            /** Bytes */
            bytes: number;
            /**
             * Checksum
             * @description SHA-256 of the delivered file.
             */
            checksum: string;
            /** Mediatype */
            mediaType: string;
        };
        /** CollectionEnvelope */
        CollectionEnvelope: {
            data: components["schemas"]["CollectionOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** CollectionListEnvelope */
        CollectionListEnvelope: {
            /** Data */
            data: components["schemas"]["CollectionSummaryOut"][];
            meta: components["schemas"]["CountMeta"];
            links: components["schemas"]["Links"];
        };
        /** CollectionOut */
        CollectionOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Shorttitle */
            shortTitle: string;
            /** Kicker */
            kicker: string;
            /** Description */
            description: string;
            /** Coverage */
            coverage: string;
            /** Videoids */
            videoIds: string[];
            /** Images */
            images: number;
            /** Artifacts */
            artifacts: number;
            /** Withsource */
            withSource: number;
            /**
             * Segmented
             * @description Records carrying a mask, and so a measurement.
             */
            segmented: number;
            /** Image */
            image: string;
            /** Imagealt */
            imageAlt: string;
            /**
             * Releases
             * @default []
             */
            releases: components["schemas"]["ReleaseOut"][];
            /**
             * Meancloudcoveroktas
             * @description Mean measured cover across the segmented frames.
             */
            meanCloudCoverOktas?: number | null;
            /**
             * Maskregistration
             * @default []
             */
            maskRegistration: components["schemas"]["MaskRegistration"][];
            /** Locationname */
            locationName?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
        };
        /**
         * CollectionSummaryOut
         * @description The listing shape: the release history replaced by the current one.
         */
        CollectionSummaryOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Shorttitle */
            shortTitle: string;
            /** Kicker */
            kicker: string;
            /** Description */
            description: string;
            /** Coverage */
            coverage: string;
            /** Videoids */
            videoIds: string[];
            /** Images */
            images: number;
            /** Artifacts */
            artifacts: number;
            /** Withsource */
            withSource: number;
            /**
             * Segmented
             * @description Records carrying a mask, and so a measurement.
             */
            segmented: number;
            /** Image */
            image: string;
            /** Imagealt */
            imageAlt: string;
            /**
             * Releases
             * @default []
             */
            releases: components["schemas"]["ReleaseOut"][];
            /**
             * Meancloudcoveroktas
             * @description Mean measured cover across the segmented frames.
             */
            meanCloudCoverOktas?: number | null;
            /**
             * Maskregistration
             * @default []
             */
            maskRegistration: components["schemas"]["MaskRegistration"][];
            /** Locationname */
            locationName?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Instrument */
            instrument?: string | null;
            /** License */
            license?: string | null;
            /** Citation */
            citation?: string | null;
            /** Doi */
            doi?: string | null;
            currentRelease?: components["schemas"]["ReleaseOut"] | null;
        };
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** CountMeta */
        CountMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Count */
            count: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: string[];
            } | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FacetValue */
        FacetValue: {
            /** Value */
            value: string | number;
            /** Label */
            label?: string | null;
            /** Count */
            count: number;
        };
        /** FacetsEnvelope */
        FacetsEnvelope: {
            data: components["schemas"]["FacetsOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** FacetsOut */
        FacetsOut: {
            /** Collections */
            collections: components["schemas"]["FacetValue"][];
            /** Sequences */
            sequences: components["schemas"]["FacetValue"][];
            /** Cloudcoveroktas */
            cloudCoverOktas: components["schemas"]["FacetValue"][];
            /** Segmentation */
            segmentation: components["schemas"]["FacetValue"][];
            /** Artifacts */
            artifacts: components["schemas"]["FacetValue"][];
            /** Seasons */
            seasons: components["schemas"]["FacetValue"][];
            /** Timesofday */
            timesOfDay: components["schemas"]["FacetValue"][];
            /** Locations */
            locations: components["schemas"]["FacetValue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageEnvelope */
        ImageEnvelope: {
            data: components["schemas"]["ImageRecordOut"];
            meta: components["schemas"]["Meta"];
            links: components["schemas"]["Links"];
        };
        /** ImagePage */
        ImagePage: {
            /** Data */
            data: components["schemas"]["ImageRecordOut"][];
            meta: components["schemas"]["PageMeta"];
            links: components["schemas"]["PageLinks"];
        };
        /**
         * ImageRecordOut
         * @description One frame.
         *
         *     ``cloudFraction`` and ``cloudCoverOktas`` are absent, not null, on a frame
         *     that carries no mask: cloud cover is measured from the mask, so without one
         *     there is no measurement to report. They are never defaulted to zero, which
         *     would invent a clear sky.
         */
        ImageRecordOut: {
            /** Id */
            id: string;
            /** Collection */
            collection: string;
            /** Release */
            release: string;
            /** Videoid */
            videoId: string;
            /** Frameindex */
            frameIndex: number;
            /** Cloudfraction */
            cloudFraction?: number | null;
            /** Cloudcoveroktas */
            cloudCoverOktas?: number | null;
            /**
             * Maskscale
             * @description Scale at which the mask was delivered relative to its frame. 1 for a correctly registered sequence; greater where the mask was rendered larger and the viewer must scale it back.
             */
            maskScale: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Image
             * @description Primary listing image: the frame, else the mask.
             */
            image: string;
            /** Sourceurl */
            sourceUrl?: string | null;
            /** Maskurl */
            maskUrl?: string | null;
            /** Hassource */
            hasSource: boolean;
            /** Hasmask */
            hasMask: boolean;
            /** Alt */
            alt: string;
            /** Tags */
            tags: string[];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactOut"][];
            /**
             * Sortkey
             * @description Capture time when known, sequence position otherwise.
             */
            sortKey: string;
            /** Capturedat */
            capturedAt?: string | null;
            /** Location */
            location?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Season */
            season?: string | null;
            /** Timeofday */
            timeOfDay?: string | null;
            /** Instrument */
            instrument?: string | null;
        };
        /** Links */
        Links: {
            /** Self */
            self: string;
        };
        /** MaskRegistration */
        MaskRegistration: {
            /** Videoid */
            videoId: string;
            /**
             * Scale
             * @description Mask size relative to the frame it segments. 1 when registered.
             */
            scale: number;
            /** Corrected */
            corrected: boolean;
        };
        /** Meta */
        Meta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
        };
        /** PageLinks */
        PageLinks: {
            /** Self */
            self: string;
            /** Next */
            next?: string | null;
        };
        /** PageMeta */
        PageMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Count */
            count: number;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** ReleaseListEnvelope */
        ReleaseListEnvelope: {
            /** Data */
            data: components["schemas"]["ReleaseOut"][];
            meta: components["schemas"]["ReleaseMeta"];
            links: components["schemas"]["Links"];
        };
        /** ReleaseMeta */
        ReleaseMeta: {
            /**
             * Apiversion
             * @default 1.0
             */
            apiVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Collection */
            collection: string;
            /** Count */
            count: number;
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Version */
            version: string;
            /** Images */
            images: number;
            /**
             * Size
             * @description Human-readable total, e.g. '10.4 MB'.
             */
            size: string;
            /** Current */
            current: boolean;
            /** Publishedat */
            publishedAt?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_list_images: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePage"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    catalog_get_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_list_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListEnvelope"];
                };
            };
        };
    };
    catalog_get_collection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_list_releases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseListEnvelope"];
                };
            };
            /** @description One or more query parameters are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description No such record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_get_facets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsEnvelope"];
                };
            };
        };
    };
    catalog_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
