/**
 * The domain types, taken from the backend's OpenAPI schema.
 *
 * `lib/api-types.ts` is generated by `npm run types:generate` and should not
 * be edited. This module gives its deeply nested definitions the short names
 * the components already use, so a component reads `ImageRecord` rather than
 * `components["schemas"]["ImageRecordOut"]`, and so a shape change in the
 * backend surfaces here as a type error rather than as a runtime surprise.
 */
import type { components } from "./api-types";

type Schemas = components["schemas"];

export type Artifact = Schemas["ArtifactOut"];
export type Release = Schemas["ReleaseOut"];
export type Coordinates = Schemas["Coordinates"];

/**
 * One frame.
 *
 * `cloudFraction` and `cloudCoverOktas` are absent on a frame with no mask:
 * cloud cover is measured from the mask, so without one there is nothing to
 * report. They are never zero-filled, which would claim a clear sky nobody
 * observed.
 */
export type ImageRecord = Schemas["ImageRecordOut"];

export type Collection = Schemas["CollectionOut"];
export type CollectionSummary = Schemas["CollectionSummaryOut"];

export type Facets = Schemas["FacetsOut"];
export type FacetValue = Schemas["FacetValue"];

export type ApiError = Schemas["ErrorDetail"];

/** One page of image records, with the cursor for the next. */
export type ImagePage = {
  records: ImageRecord[];
  total: number;
  limit: number;
  nextCursor: string | null;
};
